### ISSUE TITLE
issue with the same type model relationships

### ISSUE THREAD

**Issue by sullysheperd** [flugger/laravel-responder#10]
Hi flugger

I've been using relations with this package and it works just fine. For example if I wanna send the owner of the comment it works just fine. 

On the other hand, I wanna send the children of comments (it's a tree-style comment system like Disqus) in my api, and only then(using relations to retrieve the same type of model) I get this error:
"Data must only contain models implementing the Transformable contract."

My relation implementation seems fine as it works just fine, it's just I need it in the API but it fails :(, any idea how to fix it?

Thank your for your great package

**Comment by flugger** [comment]
Hmm, sounds like an untested scenario, I will investigate right away

**Comment by flugger** [comment]
Hmm, I can't seem to recreate your scenario, I've managed to include a nested `fruit` resource 3 times as seen from the JSON output in the following gist: https://gist.github.com/flugger/6cff6cd54ac0cae3f49dd5dc9dced5fb

What does the data you pass into the `success` method look like? And are you sure all resources included has a `transformer()` method?

**Comment by sullysheperd** [comment]
I went ahead and tried some other scenarios, it's very weird:
it works when I return my comment models (when I exclude the children comments)
so the transformer implementation in my Comment model is fine. 

it also works when I return any relation models with my other models, except my comment model! (I was wrong, it has nothing to do with returning the same model)

Also my relation implementation for comments (posts haveMany comments) seems fine as I successfully retrieve it. So what is the problem?!?!?!?!? I keep checking but I see no difference between my models.

**Comment by flugger** [comment]
This is the method from the package where the exception resides:

```php
protected function resolveModel( Collection $collection ):Transformable
{
    $class = $collection->first();

    if ( ! $class instanceof Transformable ) {
        throw new InvalidArgumentException( 'Data must only contain models implementing the Transformable contract.' );
    }
    // ...
```

It's trying to resolve a transformable model from the first item in your collection. Can you do a `dd()` on the data you pass into the `success()` method?

**Comment by sullysheperd** [comment]
Collection {#245 ▼
  #items: array:2 [▼
    0 => Comment {#239 ▼
      #connection: null
      #table: null
      #primaryKey: "id"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:10 [▶]
      #original: array:10 [▶]
      #relations: array:1 [▼
        "children" => Collection {#243 ▼
          #items: array:1 [▼
            0 => Comment {#246 ▼
              #connection: null
              #table: null
              #primaryKey: "id"
              #perPage: 15
              +incrementing: true
              +timestamps: true
              #attributes: array:10 [▼
                "id" => 10
                "body" => "asdfasdfadsf"
                "upvotes" => 0
                "downvotes" => 0
                "active" => 1
                "submission_id" => 1
                "created_at" => "2016-08-10 16:47:15"
                "updated_at" => "2016-08-10 16:47:15"
                "user_id" => 1
                "comment_id" => 9
              ]
              #original: array:10 [▼
                "id" => 10
                "body" => "asdfasdfadsf"
                "upvotes" => 0
                "downvotes" => 0
                "active" => 1
                "submission_id" => 1
                "created_at" => "2016-08-10 16:47:15"
                "updated_at" => "2016-08-10 16:47:15"
                "user_id" => 1
                "comment_id" => 9
              ]
              #relations: []
              #hidden: []
              #visible: []
              #appends: []
              #fillable: []
              #guarded: array:1 [▶]
              #dates: []
              #dateFormat: null
              #casts: []
              #touches: []
              #observables: []
              #with: []
              #morphClass: null
              +exists: true
              +wasRecentlyCreated: false
            }
          ]
        }
      ]
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [▶]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      #morphClass: null
      +exists: true
      +wasRecentlyCreated: false
    }
    1 => Comment {#240 ▼
      #connection: null
      #table: null
      #primaryKey: "id"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:10 [▼
        "id" => 10
        "body" => "asdfasdfadsf"
        "upvotes" => 0
        "downvotes" => 0
        "active" => 1
        "submission_id" => 1
        "created_at" => "2016-08-10 16:47:15"
        "updated_at" => "2016-08-10 16:47:15"
        "user_id" => 1
        "comment_id" => 9
      ]
      #original: array:10 [▼
        "id" => 10
        "body" => "asdfasdfadsf"
        "upvotes" => 0
        "downvotes" => 0
        "active" => 1
        "submission_id" => 1
        "created_at" => "2016-08-10 16:47:15"
        "updated_at" => "2016-08-10 16:47:15"
        "user_id" => 1
        "comment_id" => 9
      ]
      #relations: array:1 [▼
        "children" => Collection {#242 ▼
          #items: []
        }
      ]
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [▶]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      #morphClass: null
      +exists: true
      +wasRecentlyCreated: false
    }
  ]
}

**Comment by sullysheperd** [comment]
When I simply return the $comments (and use Laravel's api) while eager loading it, it works just fine, it loads the children as well. 

I can also return $comments (without the children) and it works fine then as well. But when I ad // `'children' => $comment->children, ` to my CommentTransfer class, it blows. 

So weird...

**Comment by flugger** [comment]
Hmm, the collection output above was pretty hard to decode, perhaps you could do a ->toArray() on it?

The comment model has a `children()` method with `$this->hasMany( Comment::class )`? What does your eager load query look like? Sorry for all the questions, I'm trying to recreate your issue, and it's quite hard without more to go on.

**Comment by flugger** [comment]
Are you also on the most recent version of the package? There has been issues reported in the past of issues when loading empty relations

**Comment by sullysheperd** [comment]
"The comment model has a children() method with $this->hasMany( Comment::class )? What does your eager load query look like? Sorry for all the questions, I'm trying to recreate your issue, and it's quite hard without more to go on."

```
public function children(){
    return $this->hasMany(Comment::class);
  }
```

this is how I eager load it:

$comments = Comment::with('children')->get();
return responder()->success( $comments );

And this is the output of toArray:

```
Collection {#245 ▼
  #items: array:2 [▼
    0 => Comment {#239 ▼
      #connection: null
      #table: null
      #primaryKey: "id"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:10 [▶]
      #original: array:10 [▼
        "id" => 9
        "body" => "this is for test"
        "upvotes" => 0
        "downvotes" => 0
        "active" => 1
        "submission_id" => 1
        "created_at" => "2016-08-10 16:47:14"
        "updated_at" => "2016-08-10 16:47:14"
        "user_id" => 1
        "comment_id" => 0
      ]
      #relations: array:1 [▼
        "children" => Collection {#243 ▼
          #items: array:1 [▼
            0 => Comment {#246 ▼
              #connection: null
              #table: null
              #primaryKey: "id"
              #perPage: 15
              +incrementing: true
              +timestamps: true
              #attributes: array:10 [▶]
              #original: array:10 [▶]
              #relations: []
              #hidden: []
              #visible: []
              #appends: []
              #fillable: []
              #guarded: array:1 [▶]
              #dates: []
              #dateFormat: null
              #casts: []
              #touches: []
              #observables: []
              #with: []
              #morphClass: null
              +exists: true
              +wasRecentlyCreated: false
            }
          ]
        }
      ]
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [▶]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      #morphClass: null
      +exists: true
      +wasRecentlyCreated: false
    }
    1 => Comment {#240 ▼
      #connection: null
      #table: null
      #primaryKey: "id"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:10 [▶]
      #original: array:10 [▶]
      #relations: array:1 [▶]
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [▶]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      #morphClass: null
      +exists: true
      +wasRecentlyCreated: false
    }
  ]
}

```

**Comment by flugger** [comment]
Hmm, this is very strange. I've created the same model as you and a `children()` relation, but still no issues. Getting the output below:

```json
"data": [
{
    "id": 1,
    "comment_id": null,
    "body": "Quo placeat eum et inventore omnis rem. Accusantium dolorem ut ea officia. Voluptatibus voluptates eum placeat. Et earum maxime et recusandae a qui odit voluptatem.",
    "children": [
        {
            "id": 2,
            "comment_id": 1,
            "body": "Voluptas delectus non magnam repudiandae illum. Maxime in deleniti minus libero rerum     non. Sint quasi alias minima alias. Ut consequatur sed repellendus."
        }
    ]
}
```

Can you paste your Comment model and CommentTransformer below?

**Comment by sullysheperd** [comment]
my Comment model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Transformers\CommentTransformer;
use Flugg\Responder\Contracts\Transformable;


class Comment extends Model implements Transformable
{


  public function user(){
    return $this->belongsTo(User::class, 'user_id');
  }

  public function submission(){
    return $this->belongsTo(Submission::class, 'submission_id');
  }

  public function parent(){
    return $this->belongsTo(Comment::class, 'comment_id');
  }

  public function children(){
    return $this->hasMany(Comment::class);
  }

  /**
   * The path to the transformer class.
   *
   * @return string|null
   */
  public static function transformer()
  {
      return CommentTransformer::class;
  }

}
```

My CommentTransfer:

```
<?php

namespace App\Transformers;

use App\Comment;
use Flugg\Responder\Transformer;

class CommentTransformer extends Transformer
{
    /**
     * Transform the model data into a generic array.
     *
     * @param  Comment $comment
     * @return array
     */
    public function transform(Comment $comment):array
    {
      return [
          'id' => (int) $comment->id,
          'submitted_by' => (string)$comment->user->username,
          'submitted_at' => (string)$comment->created_at->diffForHumans(),
          'text' => $comment->body,
          'children' => $comment->children,
          'upvotes' => (int) $comment->upvotes,
          'downvotes' => (int) $comment->downvotes,
      ];
    }
```
}

**Comment by flugger** [comment]
Hmm, I've replicated the code above and I'm still not getting any errors :(

You shouldn't have to reference your relations in your transformers as they will automatically be added for you. You can try to remove the following line from you transformer:

```php
'children' => $comment->children,
```

However, I just tested it with that line and it worked just fine. 

If it's not too much to ask, could you create a new repository where the problem occurs, so I can clone it and investigate further?

**Comment by flugger** [comment]
Also, I see you are referencing a user relation on the comment. Are you certain the User model implements the Transformable contract?

**Comment by sullysheperd** [comment]
Yes, the user works fine (the same thing works fine for users and its submissions for example). Also, when we try to get the the comments with their parents there is no user class involved (so that couldn't be an issue in this case)

**Comment by sullysheperd** [comment]
It even works when I try the same code with eager loading with parent (instead of children) and it works but with children ... :|

**Comment by flugger** [comment]
Could you perhaps create a new Github repository which replicates your issue so I can investigate further?

**Comment by sullysheperd** [comment]
Just please don't judge :D 
https://github.com/sullysheperd/voten

**Comment by flugger** [comment]
Don't worry, I'm not a judger :) 

And thank you! I see you only inlcuded the app folder though, is it possible to include the other folders as well in the repo? That way I can clone it and run `composer install` and see the error you're seeing. If you have any sensitive data in there, just remove it, I only need the files necessary to replicate the exception.

**Comment by sullysheperd** [comment]
sure, I just removed the front-end files. There is a function called "tests" in UserController file, which should do the trick(by running localhost:port/test). Also the vendor folder is complressed(should be extracted).

**Comment by flugger** [comment]
Hey, did some tests and did replicate the error when the collection was empty. This was fixed in a later patch, and I could fix it by running `composer update`. I noticed your composer.lock file had laravel-responder version 1.0.15 locked, but the most recent version is 1.1.2.

**Comment by sullysheperd** [comment]
Problem solved! Thanks man. But I still don't get it what was the problem. Cuz it's not like it had a problem with relations, also there was no empty collection. 

Thank you so much. You are very generous

**Comment by flugger** [comment]
Well, I'm not completely sure what the problem was, but there was a bug I fixed in a previous issue which could be linked to this one in some way. Glad you got it sorted out :)
